import unittest
import pygame
import math
from unittest.mock import Mock, patch
import sys
import os

# Add the directory containing the main script to Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import the main animation script (assuming it's saved as spiral_animation.py)
from response1 import draw_spiral, draw_dancing_poles

class TestSpiralAnimation(unittest.TestCase):
    """Test cases for the spiral animation program"""
    
    @classmethod
    def setUpClass(cls):
        """Initialize Pygame and create a test surface"""
        pygame.init()
        cls.screen = pygame.Surface((800, 600))
        cls.BLACK = (0, 0, 0)
        cls.WHITE = (255, 255, 255)
        cls.BLUE = (30, 144, 255)
        cls.RED = (255, 50, 50)

    def setUp(self):
        """Reset the screen before each test"""
        self.screen.fill(self.BLACK)

    def test_spiral_generation(self):
        """Test if spiral points are generated correctly"""
        center_x, center_y = 400, 300
        t = 0
        
        # Mock the pygame.draw.lines function
        with patch('pygame.draw.lines') as mock_draw:
            draw_spiral(t, center_x, center_y)
            
            # Verify that draw.lines was called
            self.assertTrue(mock_draw.called)
            
            # Verify the color used
            _, color, _, _, _ = mock_draw.call_args[0]
            self.assertEqual(color, self.BLUE)

    def test_dancing_poles_position(self):
        """Test if dancing poles are positioned correctly"""
        center_x, center_y = 400, 300
        test_times = [0, math.pi/2, math.pi, 3*math.pi/2]
        
        for t in test_times:
            # Calculate expected positions
            expected_pole1_x = center_x + 150 * math.cos(t)
            expected_pole1_y = center_y + 150 * math.sin(t)
            expected_pole2_x = center_x + 150 * math.cos(t + math.pi)
            expected_pole2_y = center_y + 150 * math.sin(t + math.pi)
            
            # Mock pygame.draw.line
            with patch('pygame.draw.line') as mock_line:
                draw_dancing_poles(t, center_x, center_y)
                
                # Verify draw.line was called twice (for both poles)
                self.assertEqual(mock_line.call_count, 2)
                
                # Verify the color used
                _, color, _, _, _ = mock_line.call_args_list[0][0]
                self.assertEqual(color, self.RED)

    def test_screen_boundaries(self):
        """Test if animation stays within screen boundaries"""
        center_x, center_y = 400, 300
        t = 0
        
        # Create mock points that would be generated by the spiral
        mock_points = [(x, y) for x in range(0, 800, 50) for y in range(0, 600, 50)]
        
        # Draw spiral and poles
        with patch('pygame.draw.lines') as mock_spiral:
            # Configure mock to return our test points
            mock_spiral.return_value = None
            mock_spiral.call_args = Mock(args=(None, None, False, mock_points, 2))
            
            draw_spiral(t, center_x, center_y)
            
            # Check spiral points
            points = mock_spiral.call_args.args[3]
            for x, y in points:
                self.assertGreaterEqual(x, -100)  # Allow some overflow for smooth animation
                self.assertLessEqual(x, 900)
                self.assertGreaterEqual(y, -100)
                self.assertLessEqual(y, 700)

    @patch('pygame.font.Font')
    def test_text_rendering(self, mock_font):
        """Test if text is rendered correctly"""
        # Mock the font rendering
        mock_font_instance = Mock()
        mock_font.return_value = mock_font_instance
        mock_font_instance.render.return_value = Mock()
        
        # Verify font size and color
        font = pygame.font.Font(None, 48)
        text = font.render("CodeRabbits", True, self.WHITE)
        
        mock_font_instance.render.assert_called_with(
            "CodeRabbits", True, self.WHITE
        )

    def test_animation_speed(self):
        """Test if animation timing is consistent"""
        t1 = 0
        t2 = t1 + 0.03  # Expected time increment
        
        # Create different mock points for each frame
        mock_points1 = [(100, 100), (200, 200)]
        mock_points2 = [(150, 150), (250, 250)]
        
        with patch('pygame.draw.lines') as mock_spiral:
            # First frame
            mock_spiral.return_value = None
            mock_spiral.call_args = Mock(args=(None, None, False, mock_points1, 2))
            draw_spiral(t1, 400, 300)
            points1 = mock_spiral.call_args.args[3]
            
            # Second frame
            mock_spiral.call_args = Mock(args=(None, None, False, mock_points2, 2))
            draw_spiral(t2, 400, 300)
            points2 = mock_spiral.call_args.args[3]
            
            # Points should be different due to rotation
            self.assertNotEqual(points1, points2)

    @classmethod
    def tearDownClass(cls):
        """Clean up Pygame"""
        pygame.quit()

if __name__ == '__main__':
    unittest.main(verbosity=2)